### ISSUE TITLE
Spree 0.70

### ISSUE THREAD

**Issue by ohmycto** [priviterag/spree_slider#1]
Hi, thanks for cool extension!
Is it compatible with Spree 0.70?

**Comment by priviterag** [comment]
Hi secoint,

unfortunately no. As you know, spree 1.0 added a Spree:: namespace to the engine.
Since I wrote after 1.0 came out, I didn't think to make it compatible with older version.

Kind regards,
Giuseppe

**Comment by ohmycto** [comment]
Here's the version, compatible with 0.70, if someone needs...
https://github.com/secoint/spree_slider/tree/0.70
