### ISSUE TITLE
Deface doesn't work with last version of Spree

### ISSUE THREAD

**Issue by javiercr** [priviterag/spree_slider#10]
With the last version of Spree from the git repository the Deface for adding the slider to the home page doesn't work. This is what I got in the rails server console:

```
Deface: 1 overrides found for 'spree/home/index'
Deface: 'add_slider' matched 1 times with '[data-hook="homepage_products"]'
Deface: [WARNING] No :original defined for 'add_slider', you should change its definition to include:
 :original => '589053f6f3e534b0be729081bdfc0378beb29cca' 
Deface: 2 overrides found for 'spree/layouts/spree_application'
Deface: 'add_analytics_header' matched 1 times with 'head'
Deface: 'add_slider' matched 0 times with '#header[data-hook]'
```

Can anyone confirm the same issue? Thanks!

**Comment by javiercr** [comment]
Ok, I found what's happening.

Look at this line:

```
Deface: 'add_slider' matched 0 times with '#header[data-hook]'
```

This deface is set with this file:
https://github.com/priviterag/spree_slider/blob/master/app/overrides/spree/layouts/spree_application/add_slider.html.erb.deface

However the header block was moved from the `layouts/spree_application.html.erb` file to a partial view (`_header.html.erb`) with this commit at Spree:
https://github.com/spree/spree/commit/02a5d68e834b4c2429c94425f1826ca8c276df6d

Therefore we need a patch for this. I'll try to make one and do a pull request.

**Comment by PragTob** [comment]
I think this can be closed :-)
