### ISSUE TITLE
Support for Spree 2.1 and Rails 4

### ISSUE THREAD

**Issue by pedropaf** [priviterag/spree_slider#18]
Hi,

I am trying to make this extension compatible with Spree 2.1 (Rails 4), removing the dependency of attr_accessible and using strong_parameters instead.

In the class Spree::Slide  I have replaced 'attr_accessible' with 'attr_accessor'. But when I add a slide, the image / published / product and position fileds are not being saved. Any ideas?

Thanks,

**Comment by JDutil** [comment]
This was fixed by https://github.com/priviterag/spree_slider/commit/d310d01272347fe0ae30d5efbab27d29b171963b
