### ISSUE TITLE
spree_slider not showing

### ISSUE THREAD

**Issue by dp6ai** [priviterag/spree_slider#2]
I'm using spree 1.0.3 with spree_slider 1.0.1 and i have 2 published slides.

When is refresh my home page i get the followng:

```
<div data-hook="" id="spree-slider">

</div>
```

I have 
gem 'spree_slider' in my Gemfile
and have run bundle install 

and then 

OSX:llos username$ rails generate spree_slider:install_anything
   identical  app/views/spree/shared/_slider.html.erb
      append  app/assets/javascripts/store/all.js
      append  app/assets/javascripts/store/all.js
      append  app/assets/javascripts/store/all.js
      insert  app/assets/stylesheets/store/all.css
         run  bundle exec rake railties:install:migrations FROM=spree_slider from "."

NOTE: Migration 20120222184238_create_slides.rb from spree_slider has been skipped. Migration with the same name already exists.
Would you like to run the migrations now? [Y/n] Y
         run  bundle exec rake db:migrate from "."

OSX:llos username$

Any idea?

thanks

DP

**Comment by dp6ai** [comment]
Hi,

Have you had a chance to look at this?

Many thanks

DP

**Comment by pirj** [comment]
Where this is div is coming from? Have you published some slider images?

**Comment by priviterag** [comment]
I did some quick test using spree 1.0.3 and it's working fine. Make sure you have some published slides (check the published field in the admin UI)

**Comment by dp6ai** [comment]
Ive created a couple of slides and published them.

This hasn't made any difference.

I've created some slides manually and removed spree_slider.

Thanks
PD

On Sun, Apr 1, 2012 at 1:34 PM, priviterag <
reply@reply.github.com
