### ISSUE TITLE
Unknown error on install...please help, I would like to use Bootstrap but wanted to try "anything" at first 

### ISSUE THREAD

**Issue by MicFin** [priviterag/spree_slider#26]
NOTE: the following error did not happen when I ran "rails generate spree_slider:install_simple_carousel"

✗ rails generate spree_slider:install_anything
   identical  app/views/spree/shared/_slider.html.erb
      append  vendor/assets/javascripts/spree/frontend/all.js
      append  vendor/assets/javascripts/spree/frontend/all.js
      append  vendor/assets/javascripts/spree/frontend/all.js
      insert  app/assets/stylesheets/store/all.css
/Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in `binread': No such file or directory - /Users/Mike/code/kindrdfood/farmstand/app/assets/stylesheets/store/all.css (Errno::ENOENT)
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:98:in`replace!'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:59:in `invoke!'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/actions.rb:94:in`action'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/actions/inject_into_file.rb:30:in `insert_into_file'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/bundler/gems/spree_slider-407ac1ade0ed/lib/generators/spree_slider/install_anything_generator.rb:14:in`install'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/invocation.rb:126:in`invoke_command'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`each'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/invocation.rb:133:in`invoke_all'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/thor-0.19.1/lib/thor/base.rb:440:in`start'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/generators.rb:156:in `invoke'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/commands/generate.rb:11:in`<top (required)>'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/polyglot-0.3.4/lib/polyglot.rb:65:in `require'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/polyglot-0.3.4/lib/polyglot.rb:65:in`require'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `block in require'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:214:in`load_dependency'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/activesupport-4.0.3/lib/active_support/dependencies.rb:229:in `require'
    from /Users/Mike/.rvm/gems/ruby-2.0.0-p353/gems/railties-4.0.3/lib/rails/commands.rb:48:in`<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in`<main>'

**Comment by priviterag** [comment]
@MicFin do you still see this issue? which version are you using?
