### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by berkes** [priviterag/spree_slider#35]
It appars as if this repo is no longer maintained: several issues and one pull-request have been open and not reacted upon for over half a year.

If the PRs, forks and issues  are an indication, the extension is used and updated by several people: there appears to be a need for a maintained version.

Can the author comment if he or she will accept pull-requests and pick up issues, or wants to appoint this to someone? Or should we pick a fork and continue there?

**Comment by priviterag** [comment]
Hi Berkes,

the repository is now part of the spree-contrib collection: https://github.com/spree-contrib/spree_slider
Please, could you merge your changes to this new repo? Thanks a lot for your work!

Kind regards,
Giuseppe
