### ISSUE TITLE
Bullets and arrows - not showing up in production - deployed via capistrano

### ISSUE THREAD

**Issue by alanalvespi** [priviterag/spree_slider#38]
I have tried precompiling the assets in local, I appreciate any idea.

**Comment by priviterag** [comment]
@alanalvespi this repository is now part of the spree-contrib collection: https://github.com/spree-contrib/spree_slider please, try with the new repo

**Comment by alanalvespi** [comment]
Ok thank you. I have switched the repo but it is the same. I am gonna close here the issue and post it there.
